@host =http://localhost
@port = 3000

@url = {{host}}:{{port}}



### GET categories
GET {{url}}/categories
Content-Type: application/json

### GET one categorie by id
GET {{url}}/categories/2
Content-Type: application/json


### DELETE one categorie by id
DELETE {{url}}/categories/3
Content-Type: application/json

### POST one category
POST {{url}}/categories
Content-Type: application/json

{
    "Nev" : "Desszertek"
}

### UPDATE one category
PATCH  {{url}}/categories/5
Content-Type: application/json

{
    "Nev" : "Vendo"
}

//------------------------------------------------------------------

### GET trafics
GET {{url}}/trafics
Content-Type: application/json


### GET trafic by id
GET {{url}}/trafics/246
Content-Type: application/json

### POST one trafic
POST {{url}}/trafics
Content-Type: application/json

{
    "Termek" : "TermekNev2",
    "Vevo" : "VevoNev2",
    "KategoriaId" : 1,
    "Egyseg" : "Egyseg",
    "Nettoar" : 200,
    "Mennyiseg" : 5,
    "Kiadva" : 1
}

### DELETE one trafic by id
DELETE {{url}}/trafics/263
Content-Type: application/json


### UPDATE one category
PATCH  {{url}}/trafics/251
Content-Type: application/json

{
    "Termek" : "Vendo"
}


//-----------------------------------


### Get  statistics
GET {{url}}/statistics
Content-Type: application/json
